/** TypeCraft - Teaching Typing through Mining and Crafting.
@link    https://github.com/kabuki-starship/kabuki-projects/typecraft
@file    /projects/typecraft/typecraft_item.cc
@author  Cale McCollough <cale.mccollough@gmail.com>
@license Copyright (C) 2014-2017 Cale McCollough <calemccollough.github.io>;
All right reserved (R). Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at www.apache.org/licenses/LICENSE-2.0.
Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License. */

#include "citem.h"

namespace typecraft {

Item::Item() {}

int Item::GetType() { return type_; }

int Item::GetVariant() { return variant_; }

int Item::GetCondition() { return condition_; }

int Item::SetContition(int condition) {
  if (condition < 0) return condition;
  condition_ = condition;
}

const char* Item::GetLabel() { return label_; }

const char* Item::SetLabel(const char* label) {
  if (label == nullptr) return nullptr;
  label_ = label;
  return label;
}

const char* Item::CloneLabel(const char* label) {
  if (label == nullptr) return nullptr;
  delete label_;
  label_ = _::StringClone(label);
  return nullptr;
}

void Item::Print(_::Log& log) {}

template <int kIndex, int kVarifant>
inline Item* ItemNumber() {
  Item items[];
  items[0]
      .Set(0, "Air", "air") items[1]
      .Set(1, Stone, "stone") items[]
      .Set(1, 1, "Granite", "stone") items[]
      .Set(1, 2, "Polished Granite", "stone") items[]
      .Set(1, 3, "Diorite", "stone") items[]
      .Set(1, 4, "Polished Diorite", "stone") items[]
      .Set(1, 5, "Andesite", "stone") items[]
      .Set(1, 6, "Polished Andesite", "stone") items[2]
      .Set(2, "Grass", "grass") items[3]
      .Set(3, "Dirt", "dirt") items[]
      .Set(3, 1, "Coarse Dirt", "dirt") items[]
      .Set(3, 2, "Podzol", "dirt") items[4]
      .Set(4, "Cobblestone", "cobblestone") items[5]
      .Set(5, "Oak Wood Plank", "planks") items[]
      .Set(5, 1, "Spruce Wood Plank", "planks") items[]
      .Set(5, 2, "Birch Wood Plank", "planks") items[]
      .Set(5, 3, "Jungle Wood Plank", "planks") items[]
      .Set(5, 4, "Acacia Wood Plank", "planks") items[]
      .Set(5, 5, "Dark Oak Wood Plank", "planks") items[]
      .Set(6, "Oak Sapling", "sapling") items[]
      .Set(6, 1, "Spruce Sapling", "sapling") items[]
      .Set(6, 2, "Birch Sapling", "sapling") items[]
      .Set(6, 3, "Jungle Sapling", "sapling") items[]
      .Set(6, 4, "Acacia Sapling", "sapling") items[]
      .Set(6, 5, "Dark Oak Sapling", "sapling") items[]
      .Set(7, "Bedrock", "bedrock") items[]
      .Set(8, "Flowing Water", "flowing_water") items[]
      .Set(9, "Still Water", "water") items[]
      .Set(10, "Flowing Lava", "flowing_lava") items[]
      .Set(11, "Still Lava", "lava") items[]
      .Set(12, "Sand", "sand") items[]
      .Set(12, 1, "Red Sand", "sand") items[]
      .Set(13, "Gravel", "gravel") items[]
      .Set(14, "Gold Ore", "gold_ore") items[]
      .Set(15, "Iron Ore", "iron_ore") items[]
      .Set(16, "Coal Ore", "coal_ore") items[]
      .Set(17, "Oak Wood", "log") items[]
      .Set(17, 1, "Spruce Wood", "log") items[]
      .Set(17, 2, "Birch Wood", "log") items[]
      .Set(17, 3, "Jungle Wood", "log") items[]
      .Set(18, "Oak Leaves", "leaves") items[]
      .Set(18, 1, "Spruce Leaves", "leaves") items[]
      .Set(18, 2, "Birch Leaves", "leaves") items[]
      .Set(18, 3, "Jungle Leaves", "leaves") items[]
      .Set(19, "Sponge", "sponge") items[]
      .Set(19, 1, "Wet Sponge", "sponge") items[]
      .Set(20, "Glass", "glass") items[]
      .Set(21, "Lapis Lazuli Ore", "lapis_ore") items[]
      .Set(22, "Lapis Lazuli Block", "lapis_block") items[]
      .Set(23, "Dispenser", "dispenser") items[]
      .Set(24, "Sandstone", "sandstone") items[]
      .Set(24, 1, "Chiseled Sandstone", "sandstone") items[]
      .Set(24, 2, "Smooth Sandstone", "sandstone") items[]
      .Set(25, "Note Block", "noteblock") items[]
      .Set(26, "Bed", "bed") items[]
      .Set(27, "Powered Rail", "golden_rail") items[]
      .Set(28, "Detector Rail", "detector_rail") items[]
      .Set(29, "Sticky Piston", "sticky_piston") items[]
      .Set(30, "Cobweb", "web") items[]
      .Set(31, "Dead Shrub", "tallgrass") items[]
      .Set(31, 1, "Grass", "tallgrass") items[]
      .Set(31, 2, "Fern", "tallgrass") items[]
      .Set(32, "Dead Bush", "deadbush") items[]
      .Set(33, "Piston", "piston") items[]
      .Set(34, "Piston Head", "piston_head") items[]
      .Set(35, "White Wool", "wool") items[]
      .Set(35, 1, "Orange Wool", "wool") items[]
      .Set(35, 2, "Magenta Wool", "wool") items[]
      .Set(35, 3, "Light Blue Wool", "wool") items[]
      .Set(35, 4, "Yellow Wool", "wool") items[]
      .Set(35, 5, "Lime Wool", "wool") items[]
      .Set(35, 6, "Pink Wool", "wool") items[]
      .Set(35, 7, "Gray Wool", "wool") items[]
      .Set(35, 8, "Light Gray Wool", "wool") items[]
      .Set(35, 9, "Cyan Wool", "wool") items[]
      .Set(35, 10, "Purple Wool", "wool") items[]
      .Set(35, 11, "Blue Wool", "wool") items[]
      .Set(35, 12, "Brown Wool", "wool") items[]
      .Set(35, 13, "Green Wool", "wool") items[]
      .Set(35, 14, "Red Wool", "wool") items[]
      .Set(35, 15, "Black Wool", "wool") items[]
      .Set(37, "Dandelion", "yellow_flower") items[]
      .Set(38, "Poppy", "red_flower") items[]
      .Set(38, 1, "Blue Orchid", "red_flower") items[]
      .Set(38, 2, "Allium", "red_flower") items[]
      .Set(38, 3, "Azure Bluet", "red_flower") items[]
      .Set(38, 4, "Red Tulip", "red_flower") items[]
      .Set(38, 5, "Orange Tulip", "red_flower") items[]
      .Set(38, 6, "White Tulip", "red_flower") items[]
      .Set(38, 7, "Pink Tulip", "red_flower") items[]
      .Set(38, 8, "Oxeye Daisy", "red_flower") items[]
      .Set(39, "Brown Mushroom", "brown_mushroom") items[]
      .Set(40, "Red Mushroom", "red_mushroom") items[]
      .Set(41, "Gold Block", "gold_block") items[]
      .Set(42, "Iron Block", "iron_block") items[]
      .Set(43, "Double Stone Slab", "double_stone_slab") items[]
      .Set(43, 1, "Double Sandstone Slab", "double_stone_slab") items[]
      .Set(43, 2, "Double Wooden Slab", "double_stone_slab") items[]
      .Set(43, 3, "Double Cobblestone Slab", "double_stone_slab") items[]
      .Set(43, 4, "Double Brick Slab", "double_stone_slab") items[]
      .Set(43, 5, "Double Stone Brick Slab", "double_stone_slab") items[]
      .Set(43, 6, "Double Nether Brick Slab", "double_stone_slab") items[]
      .Set(43, 7, "Double Quartz Slab", "double_stone_slab") items[]
      .Set(44, "Stone Slab", "stone_slab") items[]
      .Set(44, 1, "Sandstone Slab", "stone_slab") items[]
      .Set(44, 2, "Wooden Slab", "stone_slab") items[]
      .Set(44, 3, "Cobblestone Slab", "stone_slab") items[]
      .Set(44, 4, "Brick Slab", "stone_slab") items[]
      .Set(44, 5, "Stone Brick Slab", "stone_slab") items[]
      .Set(44, 6, "Nether Brick Slab", "stone_slab") items[]
      .Set(44, 7, "Quartz Slab", "stone_slab") items[]
      .Set(45, "Bricks", "brick_block") items[]
      .Set(46, "TNT", "tnt") items[]
      .Set(47, "Bookshelf", "bookshelf") items[]
      .Set(48, "Moss Stone", "mossy_cobblestone") items[]
      .Set(49, "Obsidian", "obsidian") items[]
      .Set(50, "Torch", "torch") items[]
      .Set(51, "Fire", "fire") items[]
      .Set(52, "Monster Spawner", "mob_spawner") items[]
      .Set(53, "Oak Wood Stairs", "oak_stairs") items[]
      .Set(54, "Chest", "chest") items[]
      .Set(55, "Redstone Wire", "redstone_wire") items[]
      .Set(56, "Diamond Ore", "diamond_ore") items[]
      .Set(57, "Diamond Block", "diamond_block") items[]
      .Set(58, "Crafting Table", "crafting_table") items[]
      .Set(59, "Wheat Crops", "wheat") items[]
      .Set(60, "Farmland", "farmland") items[]
      .Set(61, "Furnace", "furnace") items[]
      .Set(62, "Burning Furnace", "lit_furnace") items[]
      .Set(63, "Standing Sign Block", "standing_sign") items[]
      .Set(64, "Oak Door Block", "wooden_door") items[]
      .Set(65, "Ladder", "ladder") items[]
      .Set(66, "Rail", "rail") items[]
      .Set(67, "Cobblestone Stairs", "stone_stairs") items[]
      .Set(68, "Wall-mounted Sign Block", "wall_sign") items[]
      .Set(69, "Lever", "lever") items[]
      .Set(70, "Stone Pressure Plate", "stone_pressure_plate") items[]
      .Set(71, "Iron Door Block", "iron_door") items[]
      .Set(72, "Wooden Pressure Plate", "wooden_pressure_plate") items[]
      .Set(73, "Redstone Ore", "redstone_ore") items[]
      .Set(74, "Glowing Redstone Ore", "lit_redstone_ore") items[]
      .Set(75, "Redstone Torch (off") ", " unlit_redstone_torch ")
      items[]
      .Set(76, "Redstone Torch (on") ", " redstone_torch ")
      items[]
      .Set(77, "Stone Button", "stone_button") items[]
      .Set(78, "Snow", "snow_layer") items[]
      .Set(79, "Ice", "ice") items[]
      .Set(80, "Snow Block", "snow") items[]
      .Set(81, "Cactus", "cactus") items[]
      .Set(82, "Clay", "clay") items[]
      .Set(83, "Sugar Canes", "reeds") items[]
      .Set(84, "Jukebox", "jukebox") items[]
      .Set(85, "Oak Fence", "fence") items[]
      .Set(86, "Pumpkin", "pumpkin") items[]
      .Set(87, "Netherrack", "netherrack") items[]
      .Set(88, "Soul Sand", "soul_sand") items[]
      .Set(89, "Glowstone", "glowstone") items[]
      .Set(90, "Nether Portal", "portal") items[]
      .Set(91, "Jack o'Lantern", "lit_pumpkin") items[]
      .Set(92, "Cake Block", "cake") items[]
      .Set(93, "Redstone Repeater Block (off") ", " unpowered_repeater ")
      items[]
      .Set(94, "Redstone Repeater Block (on") ", " powered_repeater ")
      items[]
      .Set(95, "White Stained Glass", "stained_glass") items[]
      .Set(95, 1, "Orange Stained Glass", "stained_glass") items[]
      .Set(95, 2, "Magenta Stained Glass", "stained_glass") items[]
      .Set(95, 3, "Light Blue Stained Glass", "stained_glass") items[]
      .Set(95, 4, "Yellow Stained Glass", "stained_glass") items[]
      .Set(95, 5, "Lime Stained Glass", "stained_glass") items[]
      .Set(95, 6, "Pink Stained Glass", "stained_glass") items[]
      .Set(95, 7, "Gray Stained Glass", "stained_glass") items[]
      .Set(95, 8, "Light Gray Stained Glass", "stained_glass") items[]
      .Set(95, 9, "Cyan Stained Glass", "stained_glass") items[]
      .Set(95, 10, "Purple Stained Glass", "stained_glass") items[]
      .Set(95, 11, "Blue Stained Glass", "stained_glass") items[]
      .Set(95, 12, "Brown Stained Glass", "stained_glass") items[]
      .Set(95, 13, "Green Stained Glass", "stained_glass") items[]
      .Set(95, 14, "Red Stained Glass", "stained_glass") items[]
      .Set(95, 15, "Black Stained Glass", "stained_glass") items[]
      .Set(96, "Wooden Trapdoor", "trapdoor") items[]
      .Set(97, "Stone Monster Egg", "monster_egg") items[]
      .Set(97, 1, "Cobblestone Monster Egg", "monster_egg") items[]
      .Set(97, 2, "Stone Brick Monster Egg", "monster_egg") items[]
      .Set(97, 3, "Mossy Stone Brick Monster Egg", "monster_egg") items[]
      .Set(97, 4, "Cracked Stone Brick Monster Egg", "monster_egg") items[]
      .Set(97, 5, "Chiseled Stone Brick Monster Egg", "monster_egg") items[]
      .Set(98, "Stone Bricks", "stonebrick") items[]
      .Set(98, 1, "Mossy Stone Bricks", "stonebrick") items[]
      .Set(98, 2, "Cracked Stone Bricks", "stonebrick") items[]
      .Set(98, 3, "Chiseled Stone Bricks", "stonebrick") items[]
      .Set(99, "Brown Mushroom Block", "brown_mushroom_block") items[]
      .Set(100, "Red Mushroom Block", "red_mushroom_block") items[]
      .Set(101, "Iron Bars", "iron_bars") items[]
      .Set(102, "Glass Pane", "glass_pane") items[]
      .Set(103, "Melon Block", "melon_block") items[]
      .Set(104, "Pumpkin Stem", "pumpkin_stem") items[]
      .Set(105, "Melon Stem", "melon_stem") items[]
      .Set(106, "Vines", "vine") items[]
      .Set(107, "Oak Fence Gate", "fence_gate") items[]
      .Set(108, "Brick Stairs", "brick_stairs") items[]
      .Set(109, "Stone Brick Stairs", "stone_brick_stairs") items[]
      .Set(110, "Mycelium", "mycelium") items[]
      .Set(111, "Lily Pad", "waterlily") items[]
      .Set(112, "Nether Brick", "nether_brick") items[]
      .Set(113, "Nether Brick Fence", "nether_brick_fence") items[]
      .Set(114, "Nether Brick Stairs", "nether_brick_stairs") items[]
      .Set(115, "Nether Wart", "nether_wart") items[]
      .Set(116, "Enchantment Table", "enchanting_table") items[]
      .Set(117, "Brewing Stand", "brewing_stand") items[]
      .Set(118, "Cauldron", "cauldron") items[]
      .Set(119, "End Portal", "end_portal") items[]
      .Set(120, "End Portal Frame", "end_portal_frame") items[]
      .Set(121, "End Stone", "end_stone") items[]
      .Set(122, "Dragon Egg", "dragon_egg") items[]
      .Set(123, "Redstone Lamp (inactive") ", " redstone_lamp ")
      items[]
      .Set(124, "Redstone Lamp (active") ", " lit_redstone_lamp ")
      items[]
      .Set(125, "Double Oak Wood Slab", "double_wooden_slab") items[]
      .Set(125, 1, "Double Spruce Wood Slab", "double_wooden_slab") items[]
      .Set(125, 2, "Double Birch Wood Slab", "double_wooden_slab") items[]
      .Set(125, 3, "Double Jungle Wood Slab", "double_wooden_slab") items[]
      .Set(125, 4, "Double Acacia Wood Slab", "double_wooden_slab") items[]
      .Set(125, 5, "Double Dark Oak Wood Slab", "double_wooden_slab") items[]
      .Set(126, "Oak Wood Slab", "wooden_slab") items[]
      .Set(126, 1, "Spruce Wood Slab", "wooden_slab") items[]
      .Set(126, 2, "Birch Wood Slab", "wooden_slab") items[]
      .Set(126, 3, "Jungle Wood Slab", "wooden_slab") items[]
      .Set(126, 4, "Acacia Wood Slab", "wooden_slab") items[]
      .Set(126, 5, "Dark Oak Wood Slab", "wooden_slab") items[]
      .Set(127, "Cocoa", "cocoa") items[]
      .Set(128, "Sandstone Stairs", "sandstone_stairs") items[]
      .Set(129, "Emerald Ore", "emerald_ore") items[]
      .Set(130, "Ender Chest", "ender_chest") items[]
      .Set(131, "Tripwire Hook", "tripwire_hook") items[]
      .Set(132, "Tripwire", "tripwire_hook") items[]
      .Set(133, "Emerald Block", "emerald_block") items[]
      .Set(134, "Spruce Wood Stairs", "spruce_stairs") items[]
      .Set(135, "Birch Wood Stairs", "birch_stairs") items[]
      .Set(136, "Jungle Wood Stairs", "jungle_stairs") items[]
      .Set(137, "Command Block", "command_block") items[]
      .Set(138, "Beacon", "beacon") items[]
      .Set(139, "Cobblestone Wall", "cobblestone_wall") items[]
      .Set(139, 1, "Mossy Cobblestone Wall", "cobblestone_wall") items[]
      .Set(140, "Flower Pot", "flower_pot") items[]
      .Set(141, "Carrots", "carrots") items[]
      .Set(142, "Potatoes", "potatoes") items[]
      .Set(143, "Wooden Button", "wooden_button") items[]
      .Set(144, "Mob Head", "skull") items[]
      .Set(145, "Anvil", "anvil") items[]
      .Set(146, "Trapped Chest", "trapped_chest") items[]
      .Set(147,
           "Weighted Pressure Plate (light") ", " light_weighted_pressure_plate
                                             ")
      items[]
      .Set(148,
           "Weighted Pressure Plate (heavy") ", " heavy_weighted_pressure_plate
                                             ")
      items[]
      .Set(149, "Redstone Comparator (inactive") ", " unpowered_comparator ")
      items[]
      .Set(150, "Redstone Comparator (active") ", " powered_comparator ")
      items[]
      .Set(151, "Daylight Sensor", "daylight_detector") items[]
      .Set(152, "Redstone Block", "redstone_block") items[]
      .Set(153, "Nether Quartz Ore", "quartz_ore") items[]
      .Set(154, "Hopper", "hopper") items[]
      .Set(155, "Quartz Block", "quartz_block") items[]
      .Set(155, 1, "Chiseled Quartz Block", "quartz_block") items[]
      .Set(155, 2, "Pillar Quartz Block", "quartz_block") items[]
      .Set(156, "Quartz Stairs", "quartz_stairs") items[]
      .Set(157, "Activator Rail", "activator_rail") items[]
      .Set(158, "Dropper", "dropper") items[]
      .Set(159, "White Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 1, "Orange Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 2, "Magenta Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 3, "Light Blue Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 4, "Yellow Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 5, "Lime Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 6, "Pink Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 7, "Gray Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 8, "Light Gray Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 9, "Cyan Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 10, "Purple Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 11, "Blue Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 12, "Brown Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 13, "Green Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 14, "Red Hardened Clay", "stained_hardened_clay") items[]
      .Set(159, 15, "Black Hardened Clay", "stained_hardened_clay") items[]
      .Set(160, "White Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 1, "Orange Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 2, "Magenta Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 3, "Light Blue Stained Glass Pane", "stained_glass_pane")
          items[]
      .Set(160, 4, "Yellow Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 5, "Lime Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 6, "Pink Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 7, "Gray Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 8, "Light Gray Stained Glass Pane", "stained_glass_pane")
          items[]
      .Set(160, 9, "Cyan Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 10, "Purple Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 11, "Blue Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 12, "Brown Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 13, "Green Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 14, "Red Stained Glass Pane", "stained_glass_pane") items[]
      .Set(160, 15, "Black Stained Glass Pane", "stained_glass_pane") items[]
      .Set(161, "Acacia Leaves", "leaves2") items[]
      .Set(161, 1, "Dark Oak Leaves", "leaves2") items[]
      .Set(162, "Acacia Wood", "log2") items[]
      .Set(162, 1, "Dark Oak Wood", "log2") items[]
      .Set(163, "Acacia Wood Stairs", "acacia_stairs") items[]
      .Set(164, "Dark Oak Wood Stairs", "dark_oak_stairs") items[]
      .Set(165, "Slime Block", "slime") items[]
      .Set(166, "Barrier", "barrier") items[]
      .Set(167, "Iron Trapdoor", "iron_trapdoor") items[]
      .Set(168, "Prismarine", "prismarine") items[]
      .Set(168, 1, "Prismarine Bricks", "prismarine") items[]
      .Set(168, 2, "Dark Prismarine", "prismarine") items[]
      .Set(169, "Sea Lantern", "sea_lantern") items[]
      .Set(170, "Hay Bale", "hay_block") items[]
      .Set(171, "White Carpet", "carpet") items[]
      .Set(171, 1, "Orange Carpet", "carpet") items[]
      .Set(171, 2, "Magenta Carpet", "carpet") items[]
      .Set(171, 3, "Light Blue Carpet", "carpet") items[]
      .Set(171, 4, "Yellow Carpet", "carpet") items[]
      .Set(171, 5, "Lime Carpet", "carpet") items[]
      .Set(171, 6, "Pink Carpet", "carpet") items[]
      .Set(171, 7, "Gray Carpet", "carpet") items[]
      .Set(171, 8, "Light Gray Carpet", "carpet") items[]
      .Set(171, 9, "Cyan Carpet", "carpet") items[]
      .Set(171, 10, "Purple Carpet", "carpet") items[]
      .Set(171, 11, "Blue Carpet", "carpet") items[]
      .Set(171, 12, "Brown Carpet", "carpet") items[]
      .Set(171, 13, "Green Carpet", "carpet") items[]
      .Set(171, 14, "Red Carpet", "carpet") items[]
      .Set(171, 15, "Black Carpet", "carpet") items[]
      .Set(172, "Hardened Clay", "hardened_clay") items[]
      .Set(173, "Block of Coal", "coal_block") items[]
      .Set(174, "Packed Ice", "packed_ice") items[]
      .Set(175, "Sunflower", "double_plant") items[]
      .Set(175, 1, "Lilac", "double_plant") items[]
      .Set(175, 2, "Double Tallgrass", "double_plant") items[]
      .Set(175, 3, "Large Fern", "double_plant") items[]
      .Set(175, 4, "Rose Bush", "double_plant") items[]
      .Set(175, 5, "Peony", "double_plant") items[]
      .Set(176, "Free-standing Banner", "standing_banner") items[]
      .Set(177, "Wall-mounted Banner", "wall_banner") items[]
      .Set(178, "Inverted Daylight Sensor", "daylight_detector_inverted")
          items[]
      .Set(179, "Red Sandstone", "red_sandstone") items[]
      .Set(179, 1, "Chiseled Red Sandstone", "red_sandstone") items[]
      .Set(179, 2, "Smooth Red Sandstone", "red_sandstone") items[]
      .Set(180, "Red Sandstone Stairs", "red_sandstone_stairs") items[]
      .Set(181, "Double Red Sandstone Slab", "double_stone_slab2") items[]
      .Set(182, "Red Sandstone Slab", "stone_slab2") items[]
      .Set(183, "Spruce Fence Gate", "spruce_fence_gate") items[]
      .Set(184, "Birch Fence Gate", "birch_fence_gate") items[]
      .Set(185, "Jungle Fence Gate", "jungle_fence_gate") items[]
      .Set(186, "Dark Oak Fence Gate", "dark_oak_fence_gate") items[]
      .Set(187, "Acacia Fence Gate", "acacia_fence_gate") items[]
      .Set(188, "Spruce Fence", "spruce_fence") items[]
      .Set(189, "Birch Fence", "birch_fence") items[]
      .Set(190, "Jungle Fence", "jungle_fence") items[]
      .Set(191, "Dark Oak Fence", "dark_oak_fence") items[]
      .Set(192, "Acacia Fence", "acacia_fence") items[]
      .Set(193, "Spruce Door Block", "spruce_door") items[]
      .Set(194, "Birch Door Block", "birch_door") items[]
      .Set(195, "Jungle Door Block", "jungle_door") items[]
      .Set(196, "Acacia Door Block", "acacia_door") items[]
      .Set(197, "Dark Oak Door Block", "dark_oak_door") items[]
      .Set(198, "End Rod", "end_rod") items[]
      .Set(199, "Chorus Plant", "chorus_plant") items[]
      .Set(200, "Chorus Flower", "chorus_flower") items[]
      .Set(201, "Purpur Block", "purpur_block") items[]
      .Set(202, "Purpur Pillar", "purpur_pillar") items[]
      .Set(203, "Purpur Stairs", "purpur_stairs") items[]
      .Set(204, "Purpur Double Slab", "purpur_double_slab") items[]
      .Set(205, "Purpur Slab", "purpur_slab") items[]
      .Set(206, "End Stone Bricks", "end_bricks") items[]
      .Set(207, "Beetroot Block", "beetroots") items[]
      .Set(208, "Grass Path", "grass_path") items[]
      .Set(209, "End Gateway", "end_gateway") items[]
      .Set(210, "Repeating Command Block", "repeating_command_block") items[]
      .Set(211, "Chain Command Block", "chain_command_block") items[]
      .Set(212, "Frosted Ice", "frosted_ice") items[]
      .Set(213, "Magma Block", "magma") items[]
      .Set(214, "Nether Wart Block", "nether_wart_block") items[]
      .Set(215, "Red Nether Brick", "red_nether_brick") items[]
      .Set(216, "Bone Block", "bone_block") items[]
      .Set(217, "Structure Void", "structure_void") items[]
      .Set(218, "Observer", "observer") items[]
      .Set(219, "White Shulker Box", "white_shulker_box") items[]
      .Set(220, "Orange Shulker Box", "orange_shulker_box") items[]
      .Set(221, "Magenta Shulker Box", "magenta_shulker_box") items[]
      .Set(222, "Light Blue Shulker Box", "light_blue_shulker_box") items[]
      .Set(223, "Yellow Shulker Box", "yellow_shulker_box") items[]
      .Set(224, "Lime Shulker Box", "lime_shulker_box") items[]
      .Set(225, "Pink Shulker Box", "pink_shulker_box") items[]
      .Set(226, "Gray Shulker Box", "gray_shulker_box") items[]
      .Set(227, "Light Gray Shulker Box", "silver_shulker_box") items[]
      .Set(228, "Cyan Shulker Box", "cyan_shulker_box") items[]
      .Set(229, "Purple Shulker Box", "purple_shulker_box") items[]
      .Set(230, "Blue Shulker Box", "blue_shulker_box") items[]
      .Set(231, "Brown Shulker Box", "brown_shulker_box") items[]
      .Set(232, "Green Shulker Box", "green_shulker_box") items[]
      .Set(233, "Red Shulker Box", "red_shulker_box") items[]
      .Set(234, "Black Shulker Box", "black_shulker_box") items[]
      .Set(235, "White Glazed Terracotta", "white_glazed_terracotta") items[]
      .Set(236, "Orange Glazed Terracotta", "orange_glazed_terracotta") items[]
      .Set(237, "Magenta Glazed Terracotta", "magenta_glazed_terracotta")
          items[]
      .Set(238, "Light Blue Glazed Terracotta", "light_blue_glazed_terracotta")
          items[]
      .Set(239, "Yellow Glazed Terracotta", "yellow_glazed_terracotta") items[]
      .Set(240, "Lime Glazed Terracotta", "lime_glazed_terracotta") items[]
      .Set(241, "Pink Glazed Terracotta", "pink_glazed_terracotta") items[]
      .Set(242, "Gray Glazed Terracotta", "gray_glazed_terracotta") items[]
      .Set(243, "Light Gray Glazed Terracotta", "light_gray_glazed_terracotta")
          items[]
      .Set(244, "Cyan Glazed Terracotta", "cyan_glazed_terracotta") items[]
      .Set(245, "Purple Glazed Terracotta", "purple_glazed_terracotta") items[]
      .Set(246, "Blue Glazed Terracotta", "blue_glazed_terracotta") items[]
      .Set(247, "Brown Glazed Terracotta", "brown_glazed_terracotta") items[]
      .Set(248, "Green Glazed Terracotta", "green_glazed_terracotta") items[]
      .Set(249, "Red Glazed Terracotta", "red_glazed_terracotta") items[]
      .Set(250, "Black Glazed Terracotta", "black_glazed_terracotta") items[]
      .Set(251, "White Concrete", "concrete") items[]
      .Set(251, 1, "Orange Concrete", "concrete") items[]
      .Set(251, 2, "Magenta Concrete", "concrete") items[]
      .Set(251, 3, "Light Blue Concrete", "concrete") items[]
      .Set(251, 4, "Yellow Concrete", "concrete") items[]
      .Set(251, 5, "Lime Concrete", "concrete") items[]
      .Set(251, 6, "Pink Concrete", "concrete") items[]
      .Set(251, 7, "Gray Concrete", "concrete") items[]
      .Set(251, 8, "Light Gray Concrete", "concrete") items[]
      .Set(251, 9, "Cyan Concrete", "concrete") items[]
      .Set(251, 10, "Purple Concrete", "concrete") items[]
      .Set(251, 11, "Blue Concrete", "concrete") items[]
      .Set(251, 12, "Brown Concrete", "concrete") items[]
      .Set(251, 13, "Green Concrete", "concrete") items[]
      .Set(251, 14, "Red Concrete", "concrete") items[]
      .Set(251, 15, "Black Concrete", "concrete") items[]
      .Set(252, "White Concrete Powder", "concrete_powder") items[]
      .Set(252, 1, "Orange Concrete Powder", "concrete_powder") items[]
      .Set(252, 2, "Magenta Concrete Powder", "concrete_powder") items[]
      .Set(252, 3, "Light Blue Concrete Powder", "concrete_powder") items[]
      .Set(252, 4, "Yellow Concrete Powder", "concrete_powder") items[]
      .Set(252, 5, "Lime Concrete Powder", "concrete_powder") items[]
      .Set(252, 6, "Pink Concrete Powder", "concrete_powder") items[]
      .Set(252, 7, "Gray Concrete Powder", "concrete_powder") items[]
      .Set(252, 8, "Light Gray Concrete Powder", "concrete_powder") items[]
      .Set(252, 9, "Cyan Concrete Powder", "concrete_powder") items[]
      .Set(252, 10, "Purple Concrete Powder", "concrete_powder") items[]
      .Set(252, 11, "Blue Concrete Powder", "concrete_powder") items[]
      .Set(252, 12, "Brown Concrete Powder", "concrete_powder") items[]
      .Set(252, 13, "Green Concrete Powder", "concrete_powder") items[]
      .Set(252, 14, "Red Concrete Powder", "concrete_powder") items[]
      .Set(252, 15, "Black Concrete Powder", "concrete_powder") items[]
      .Set(255, "Structure Block", "structure_block") items[]
      .Set(256, "Iron Shovel", "iron_shovel") items[]
      .Set(257, "Iron Pickaxe", "iron_pickaxe") items[]
      .Set(258, "Iron Axe", "iron_axe") items[]
      .Set(259, "Flint and Steel", "flint_and_steel") items[]
      .Set(260, "Apple", "apple") items[]
      .Set(261, "Bow", "bow") items[]
      .Set(262, "Arrow", "arrow") items[]
      .Set(263, "Coal", "coal") items[]
      .Set(263, 1, "Charcoal", "coal") items[]
      .Set(264, "Diamond", "diamond") items[]
      .Set(265, "Iron Ingot", "iron_ingot") items[]
      .Set(266, "Gold Ingot", "gold_ingot") items[]
      .Set(267, "Iron Sword", "iron_sword") items[]
      .Set(268, "Wooden Sword", "wooden_sword") items[]
      .Set(269, "Wooden Shovel", "wooden_shovel") items[]
      .Set(270, "Wooden Pickaxe", "wooden_pickaxe") items[]
      .Set(271, "Wooden Axe", "wooden_axe") items[]
      .Set(272, "Stone Sword", "stone_sword") items[]
      .Set(273, "Stone Shovel", "stone_shovel") items[]
      .Set(274, "Stone Pickaxe", "stone_pickaxe") items[]
      .Set(275, "Stone Axe", "stone_axe") items[]
      .Set(276, "Diamond Sword", "diamond_sword") items[]
      .Set(277, "Diamond Shovel", "diamond_shovel") items[]
      .Set(278, "Diamond Pickaxe", "diamond_pickaxe") items[]
      .Set(279, "Diamond Axe", "diamond_axe") items[]
      .Set(280, "Stick", "stick") items[]
      .Set(281, "Bowl", "bowl") items[]
      .Set(282, "Mushroom Stew", "mushroom_stew") items[]
      .Set(283, "Golden Sword", "golden_sword") items[]
      .Set(284, "Golden Shovel", "golden_shovel") items[]
      .Set(285, "Golden Pickaxe", "golden_pickaxe") items[]
      .Set(286, "Golden Axe", "golden_axe") items[]
      .Set(287, "String", "string") items[]
      .Set(288, "Feather", "feather") items[]
      .Set(289, "Gunpowder", "gunpowder") items[]
      .Set(290, "Wooden Hoe", "wooden_hoe") items[]
      .Set(291, "Stone Hoe", "stone_hoe") items[]
      .Set(292, "Iron Hoe", "iron_hoe") items[]
      .Set(293, "Diamond Hoe", "diamond_hoe") items[]
      .Set(294, "Golden Hoe", "golden_hoe") items[]
      .Set(295, "Wheat Seeds", "wheat_seeds") items[]
      .Set(296, "Wheat", "wheat") items[]
      .Set(297, "Bread", "bread") items[]
      .Set(298, "Leather Helmet", "leather_helmet") items[]
      .Set(299, "Leather Tunic", "leather_chestplate") items[]
      .Set(300, "Leather Pants", "leather_leggings") items[]
      .Set(301, "Leather Boots", "leather_boots") items[]
      .Set(302, "Chainmail Helmet", "chainmail_helmet") items[]
      .Set(303, "Chainmail Chestplate", "chainmail_chestplate") items[]
      .Set(304, "Chainmail Leggings", "chainmail_leggings") items[]
      .Set(305, "Chainmail Boots", "chainmail_boots") items[]
      .Set(306, "Iron Helmet", "iron_helmet") items[]
      .Set(307, "Iron Chestplate", "iron_chestplate") items[]
      .Set(308, "Iron Leggings", "iron_leggings") items[]
      .Set(309, "Iron Boots", "iron_boots") items[]
      .Set(310, "Diamond Helmet", "diamond_helmet") items[]
      .Set(311, "Diamond Chestplate", "diamond_chestplate") items[]
      .Set(312, "Diamond Leggings", "diamond_leggings") items[]
      .Set(313, "Diamond Boots", "diamond_boots") items[]
      .Set(314, "Golden Helmet", "golden_helmet") items[]
      .Set(315, "Golden Chestplate", "golden_chestplate") items[]
      .Set(316, "Golden Leggings", "golden_leggings") items[]
      .Set(317, "Golden Boots", "golden_boots") items[]
      .Set(318, "Flint", "flint") items[]
      .Set(319, "Raw Porkchop", "porkchop") items[]
      .Set(320, "Cooked Porkchop", "cooked_porkchop") items[]
      .Set(321, "Painting", "painting") items[]
      .Set(322, "Golden Apple", "golden_apple") items[]
      .Set(322, 1, "Enchanted Golden Apple", "golden_apple") items[]
      .Set(323, "Sign", "sign") items[]
      .Set(324, "Oak Door", "wooden_door") items[]
      .Set(325, "Bucket", "bucket") items[]
      .Set(326, "Water Bucket", "water_bucket") items[]
      .Set(327, "Lava Bucket", "lava_bucket") items[]
      .Set(328, "Minecart", "minecart") items[]
      .Set(329, "Saddle", "saddle") items[]
      .Set(330, "Iron Door", "iron_door") items[]
      .Set(331, "Redstone", "redstone") items[]
      .Set(332, "Snowball", "snowball") items[]
      .Set(333, "Oak Boat", "boat") items[]
      .Set(334, "Leather", "leather") items[]
      .Set(335, "Milk Bucket", "milk_bucket") items[]
      .Set(336, "Brick", "brick") items[]
      .Set(337, "Clay", "clay_ball") items[]
      .Set(338, "Sugar Canes", "reeds") items[]
      .Set(339, "Paper", "paper") items[]
      .Set(340, "Book", "book") items[]
      .Set(341, "Slimeball", "slime_ball") items[]
      .Set(342, "Minecart with Chest", "chest_minecart") items[]
      .Set(343, "Minecart with Furnace", "furnace_minecart") items[]
      .Set(344, "Egg", "egg") items[]
      .Set(345, "Compass", "compass") items[]
      .Set(346, "Fishing Rod", "fishing_rod") items[]
      .Set(347, "Clock", "clock") items[]
      .Set(348, "Glowstone Dust", "glowstone_dust") items[]
      .Set(349, "Raw Fish", "fish") items[]
      .Set(349, 1, "Raw Salmon", "fish") items[]
      .Set(349, 2, "Clownfish", "fish") items[]
      .Set(349, 3, "Pufferfish", "fish") items[]
      .Set(350, "Cooked Fish", "cooked_fish") items[]
      .Set(350, 1, "Cooked Salmon", "cooked_fish") items[]
      .Set(351, "Ink Sack", "dye") items[]
      .Set(351, 1, "Rose Red", "dye") items[]
      .Set(351, 2, "Cactus Green", "dye") items[]
      .Set(351, 3, "Coco Beans", "dye") items[]
      .Set(351, 4, "Lapis Lazuli", "dye") items[]
      .Set(351, 5, "Purple Dye", "dye") items[]
      .Set(351, 6, "Cyan Dye", "dye") items[]
      .Set(351, 7, "Light Gray Dye", "dye") items[]
      .Set(351, 8, "Gray Dye", "dye") items[]
      .Set(351, 9, "Pink Dye", "dye") items[]
      .Set(351, 10, "Lime Dye", "dye") items[]
      .Set(351, 11, "Dandelion Yellow", "dye") items[]
      .Set(351, 12, "Light Blue Dye", "dye") items[]
      .Set(351, 13, "Magenta Dye", "dye") items[]
      .Set(351, 14, "Orange Dye", "dye") items[]
      .Set(351, 15, "Bone Meal", "dye") items[]
      .Set(352, "Bone", "bone") items[]
      .Set(353, "Sugar", "sugar") items[]
      .Set(354, "Cake", "cake") items[]
      .Set(355, "Bed", "bed") items[]
      .Set(356, "Redstone Repeater", "repeater") items[]
      .Set(357, "Cookie", "cookie") items[]
      .Set(358, "Map", "filled_map") items[]
      .Set(359, "Shears", "shears") items[]
      .Set(360, "Melon", "melon") items[]
      .Set(361, "Pumpkin Seeds", "pumpkin_seeds") items[]
      .Set(362, "Melon Seeds", "melon_seeds") items[]
      .Set(363, "Raw Beef", "beef") items[]
      .Set(364, "Steak", "cooked_beef") items[]
      .Set(365, "Raw Chicken", "chicken") items[]
      .Set(366, "Cooked Chicken", "cooked_chicken") items[]
      .Set(367, "Rotten Flesh", "rotten_flesh") items[]
      .Set(368, "Ender Pearl", "ender_pearl") items[]
      .Set(369, "Blaze Rod", "blaze_rod") items[]
      .Set(370, "Ghast Tear", "ghast_tear") items[]
      .Set(371, "Gold Nugget", "gold_nugget") items[]
      .Set(372, "Nether Wart", "nether_wart") items[]
      .Set(373, "Potion", "potion") items[]
      .Set(374, "Glass Bottle", "glass_bottle") items[]
      .Set(375, "Spider Eye", "spider_eye") items[]
      .Set(376, "Fermented Spider Eye", "fermented_spider_eye") items[]
      .Set(377, "Blaze Powder", "blaze_powder") items[]
      .Set(378, "Magma Cream", "magma_cream") items[]
      .Set(379, "Brewing Stand", "brewing_stand") items[]
      .Set(380, "Cauldron", "cauldron") items[]
      .Set(381, "Eye of Ender", "ender_eye") items[]
      .Set(382, "Glistering Melon", "speckled_melon") items[]
      .Set(383, 4, "Spawn Elder Guardian", "spawn_egg") items[]
      .Set(383, 5, "Spawn Wither Skeleton", "spawn_egg") items[]
      .Set(383, 6, "Spawn Stray", "spawn_egg") items[]
      .Set(383, 23, "Spawn Husk", "spawn_egg") items[]
      .Set(383, 27, "Spawn Zombie Villager", "spawn_egg") items[]
      .Set(383, 28, "Spawn Skeleton Horse", "spawn_egg") items[]
      .Set(383, 29, "Spawn Zombie Horse", "spawn_egg") items[]
      .Set(383, 31, "Spawn Donkey", "spawn_egg") items[]
      .Set(383, 32, "Spawn Mule", "spawn_egg") items[]
      .Set(383, 34, "Spawn Evoker", "spawn_egg") items[]
      .Set(383, 35, "Spawn Vex", "spawn_egg") items[]
      .Set(383, 36, "Spawn Vindicator", "spawn_egg") items[]
      .Set(383, 50, "Spawn Creeper", "spawn_egg") items[]
      .Set(383, 51, "Spawn Skeleton", "spawn_egg") items[]
      .Set(383, 52, "Spawn Spider", "spawn_egg") items[]
      .Set(383, 54, "Spawn Zombie", "spawn_egg") items[]
      .Set(383, 55, "Spawn Slime", "spawn_egg") items[]
      .Set(383, 56, "Spawn Ghast", "spawn_egg") items[]
      .Set(383, 57, "Spawn Zombie Pigman", "spawn_egg") items[]
      .Set(383, 58, "Spawn Enderman", "spawn_egg") items[]
      .Set(383, 59, "Spawn Cave Spider", "spawn_egg") items[]
      .Set(383, 60, "Spawn Silverfish", "spawn_egg") items[]
      .Set(383, 61, "Spawn Blaze", "spawn_egg") items[]
      .Set(383, 62, "Spawn Magma Cube", "spawn_egg") items[]
      .Set(383, 65, "Spawn Bat", "spawn_egg") items[]
      .Set(383, 66, "Spawn Witch", "spawn_egg") items[]
      .Set(383, 67, "Spawn Endermite", "spawn_egg") items[]
      .Set(383, 68, "Spawn Guardian", "spawn_egg") items[]
      .Set(383, 69, "Spawn Shulker", "spawn_egg") items[]
      .Set(383, 90, "Spawn Pig", "spawn_egg") items[]
      .Set(383, 91, "Spawn Sheep", "spawn_egg") items[]
      .Set(383, 92, "Spawn Cow", "spawn_egg") items[]
      .Set(383, 93, "Spawn Chicken", "spawn_egg") items[]
      .Set(383, 94, "Spawn Squid", "spawn_egg") items[]
      .Set(383, 95, "Spawn Wolf", "spawn_egg") items[]
      .Set(383, 96, "Spawn Mooshroom", "spawn_egg") items[]
      .Set(383, 98, "Spawn Ocelot", "spawn_egg") items[]
      .Set(383, 100, "Spawn Horse", "spawn_egg") items[]
      .Set(383, 101, "Spawn Rabbit", "spawn_egg") items[]
      .Set(383, 102, "Spawn Polar Bear", "spawn_egg") items[]
      .Set(383, 103, "Spawn Llama", "spawn_egg") items[]
      .Set(383, 120, "Spawn Villager", "spawn_egg") items[]
      .Set(384, "Bottle o' Enchanting", "experience_bottle") items[]
      .Set(385, "Fire Charge", "fire_charge") items[]
      .Set(386, "Book and Quill", "writable_book") items[]
      .Set(387, "Written Book", "written_book") items[]
      .Set(388, "Emerald", "emerald") items[]
      .Set(389, "Item Frame", "item_frame") items[]
      .Set(390, "Flower Pot", "flower_pot") items[]
      .Set(391, "Carrot", "carrot") items[]
      .Set(392, "Potato", "potato") items[]
      .Set(393, "Baked Potato", "baked_potato") items[]
      .Set(394, "Poisonous Potato", "poisonous_potato") items[]
      .Set(395, "Empty Map", "map") items[]
      .Set(396, "Golden Carrot", "golden_carrot") items[]
      .Set(397, "Mob Head (Skeleton") ", " skull ")
      items[]
      .Set(397, 1, "Mob Head (Wither Skeleton") ", " skull ")
      items[]
      .Set(397, 2, "Mob Head (Zombie") ", " skull ")
      items[]
      .Set(397, 3, "Mob Head (Human") ", " skull ")
      items[]
      .Set(397, 4, "Mob Head (Creeper") ", " skull ")
      items[]
      .Set(397, 5, "Mob Head (Dragon") ", " skull ")
      items[]
      .Set(398, "Carrot on a Stick", "carrot_on_a_stick") items[]
      .Set(399, "Nether Star", "nether_star") items[]
      .Set(400, "Pumpkin Pie", "pumpkin_pie") items[]
      .Set(401, "Firework Rocket", "fireworks") items[]
      .Set(402, "Firework Star", "firework_charge") items[]
      .Set(403, "Enchanted Book", "enchanted_book") items[]
      .Set(404, "Redstone Comparator", "comparator") items[]
      .Set(405, "Nether Brick", "netherbrick") items[]
      .Set(406, "Nether Quartz", "quartz") items[]
      .Set(407, "Minecart with TNT", "tnt_minecart") items[]
      .Set(408, "Minecart with Hopper", "hopper_minecart") items[]
      .Set(409, "Prismarine Shard", "prismarine_shard") items[]
      .Set(410, "Prismarine Crystals", "prismarine_crystals") items[]
      .Set(411, "Raw Rabbit", "rabbit") items[]
      .Set(412, "Cooked Rabbit", "cooked_rabbit") items[]
      .Set(413, "Rabbit Stew", "rabbit_stew") items[]
      .Set(414, "Rabbit's Foot", "rabbit_foot") items[]
      .Set(415, "Rabbit Hide", "rabbit_hide") items[]
      .Set(416, "Armor Stand", "armor_stand") items[]
      .Set(417, "Iron Horse Armor", "iron_horse_armor") items[]
      .Set(418, "Golden Horse Armor", "golden_horse_armor") items[]
      .Set(419, "Diamond Horse Armor", "diamond_horse_armor") items[]
      .Set(420, "Lead", "lead") items[]
      .Set(421, "Name Tag", "name_tag") items[]
      .Set(422, "Minecart with Command Block", "command_block_minecart") items[]
      .Set(423, "Raw Mutton", "mutton") items[]
      .Set(424, "Cooked Mutton", "cooked_mutton") items[]
      .Set(425, "Banner", "banner") items[]
      .Set(427, "Spruce Door", "spruce_door") items[]
      .Set(428, "Birch Door", "birch_door") items[]
      .Set(429, "Jungle Door", "jungle_door") items[]
      .Set(430, "Acacia Door", "acacia_door") items[]
      .Set(431, "Dark Oak Door", "dark_oak_door") items[]
      .Set(432, "Chorus Fruit", "chorus_fruit") items[]
      .Set(433, "Popped Chorus Fruit", "popped_chorus_fruit") items[]
      .Set(434, "Beetroot", "beetroot") items[]
      .Set(435, "Beetroot Seeds", "beetroot_seeds") items[]
      .Set(436, "Beetroot Soup", "beetroot_soup") items[]
      .Set(437, "Dragon's Breath", "dragon_breath") items[]
      .Set(438, "Splash Potion", "splash_potion") items[]
      .Set(439, "Spectral Arrow", "spectral_arrow") items[]
      .Set(440, "Tipped Arrow", "tipped_arrow") items[]
      .Set(441, "Lingering Potion", "lingering_potion") items[]
      .Set(442, "Shield", "shield") items[]
      .Set(443, "Elytra", "elytra") items[]
      .Set(444, "Spruce Boat", "spruce_boat") items[]
      .Set(445, "Birch Boat", "birch_boat") items[]
      .Set(446, "Jungle Boat", "jungle_boat") items[]
      .Set(447, "Acacia Boat", "acacia_boat") items[]
      .Set(448, "Dark Oak Boat", "dark_oak_boat") items[]
      .Set(449, "Totem of Undying", "totem_of_undying") items[]
      .Set(450, "Shulker Shell", "shulker_shell") items[]
      .Set(452, "Iron Nugget", "iron_nugget") items[]
      .Set(2256, "13 Disc", "record_13") items[]
      .Set(2257, "Cat Disc", "record_cat") items[]
      .Set(2258, "Blocks Disc", "record_blocks") items[]
      .Set(2259, "Chirp Disc", "record_chirp") items[]
      .Set(2260, "Far Disc", "record_far") items[]
      .Set(2261, "Mall Disc", "record_mall") items[]
      .Set(2262, "Mellohi Disc", "record_mellohi") items[]
      .Set(2263, "Stal Disc", "record_stal") items[]
      .Set(2264, "Strad Disc", "record_strad") items[]
      .Set(2265, "Ward Disc", "record_ward") items[]
      .Set(2266, "11 Disc", "record_11") items[]
      .Set(2267, "Wait Disc", "record_wait")

          return nullptr;
}
}  // namespace typecraft
