#undef PRINT
#undef PRINTF
#undef PAUSE
#undef PAUSEF
#undef PRINT_HEADING
#undef PRINT_LINE
#undef TEST_BEGIN
#undef CHECK
#undef COMPARE
#undef ASSERT
#undef AVOW
#undef TEST_END
#undef PRINT_DATE
#undef DPRINT
#undef DPRINTF
#undef DPAUSE
#undef DPAUSEF
#undef DPRINT_HEADING
#undef DPRINT_LINE
#undef DTEST_BEGIN
#undef DCHECK
#undef DCOMPARE
#undef DASSERT
#undef DAVOW
#undef DPRINT_DATE
#undef SEAM_N
