#define KABUKI_TOOLKIT_PRO SCRIPT2_RELEASE
#define KABUKI_TOOLKIT_PRO_GIT KABUKI_TOOLKIT_PRO
#define KABUKI_TOOLKIT_PRO_PROJECT KABUKI_TOOLKIT_PRO + 1
#define KABUKI_TOOLKIT_PRO_SCHEDULE KABUKI_TOOLKIT_PRO + 2
#define KABUKI_TOOLKIT_PRO_TASK KABUKI_TOOLKIT_PRO + 3
#define KABUKI_TOOLKIT_PRO_WORKSPACE KABUKI_TOOLKIT_PRO + 4
#define KABUKI_TOOLKIT_PRO_RELEASE
