#include "../../script2/_seams/_seams.inl"
#include "../code/_seams.inl"
#include "../gui/_seams.inl"
#include "../imul/_seams.inl"
#include "../pro/_seams.inl"
#include "../touch/_seams.inl"
#include "../who/_seams.inl"
